### ISSUE TITLE
[TSC] Discuss the expansion of the Technical Steering Committee

### ISSUE THREAD

**Issue by fidencio** [confidential-containers/confidential-containers#144]
The TSC (Technical Steering Committeee), has been around since the project has been accepted by CNCF, and as of right now (Aug 7th, 2023) the only discussion about expansion, election, renewing process, of the TSC members, has been stale for 6+ months (see: https://github.com/confidential-containers/confidential-containers/pull/56).

Since the project joined CNCF, we've seen 2 situations that would deserve at least a discussion on how to expand the group.
1. Give voice to the companies who're joining the projects, so they can help to steer the community in a direction they can also take advantage of the project
2. Give voice to the projects being consumed by Confidential Containers, so they can help the technical steering committee to take informed decisions based on the current state and plans of the projects they're consuming, and with that have a better alignment and reduce the chances of friction with such projects.

I'd like to hear from the current TSC what's their take about this suggestion.

**Comment by mkbhanda** [comment]
I would like to further suggest that in addition to potentially expanding the TSC, in the spirit of inclusion and sharing opportunities (or pain) that the TSC members be open to re-election/rotation.

**Comment by fidencio** [comment]
2 weeks passed, with zero engagement from the TSC in this issue.

**Comment by TheFoxAtWork** [comment]
@mauilion @dzolotusky would u check with TAG Security on who is conducting this annual review? From our instructions on reviews we have an item in governance this should be linked into.

**Comment by fitzthum** [comment]
So when the TSC was initially formed, we opted for a corporate structure. The idea behind this was to keep things as simple as possible. This was always seen as a somewhat short-term approach, but frankly I'm not sure that we've reached the point where we need to make radical changes.

It seems that two main concerns have been raised here. First, representation of projects on the TSC. I assume this is mainly in reference to the Kata project. I think we should consider how to best collaborate with the Kata community moving forward, especially once the releases are more closely linked. At the moment, there are two members of the Kata AC on the CoCo TSC, so I am not sure that I see an obvious issue with representation. Is that not satisfactory or is there another project that we should be thinking about.

There is also a question about rotation of the TSC. In general I think rotating project leadership is a good idea. Our corporate structure does not preclude this. Currently the charter does not include a provision for this, but I will update the outstanding PR to add one. If there are concerns that the TSC should be rotated, for now these should be taken up within each company.


Aside from these immediate issues, I think there are some deeper questions about the TSC. I think there is some mismatch between the expectations and reality of the TSC. I have been thinking about how to address this, and I am working on a plan that includes changing the name of the TSC, explicitly enumerating the TSCs roles and responsibilities, etc. Hopefully this can spark a good discussion about how we want to adjust governance as we look towards incubation. I have not discussed this plan yet because I do not want to distract from our efforts with the merge to main. I see it as part of the timeline for release v1.0.0.

**Comment by dbuono** [comment]
> 2 weeks passed, with zero engagement from the TSC in this issue.

I am not part of the TSC, but I don't agree with this statement. I remember you bringing the argument up in the community meeting of August 10th, and there was some discussion about it from two members of the TSC. They presented their view that, while they agree with you on the need for the TSC to set-up a clear mechanism for expansion and re-election/rotation, they don't see this urgency at this point, since the community is really focused on the merge to kata main.

As a matter of fact, I'd bring the counter point: two weeks have passed, with zero engagement from the community in this issue. From my point of view, this means that the community at large doesn't really see this as a big issue. 

But you may be right, and this may be an important issue right now. You present two situations that require action in your issue. It would probably help convincing the TSC that this is what the community wants and need right now if there were practical examples of which companies and projects are seeing a need for representation. Otherwise, it really looks like this is not something the community cares about right now.

**Comment by fidencio** [comment]
> This was always seen as a somewhat short-term approach, but frankly I'm not sure that we've reached the point where we need to make radical changes.

The suggestion on the issue was to have this discussion happening, which unfortunately only got traction after a push, this is sad from the community point of view.

> At the moment, there are two members of the Kata AC on the CoCo TSC, so I am not sure that I see an obvious issue with representation. Is that not satisfactory or is there another project that we should be thinking about?

As the corporate approach has been chosen, those members are representing RivOS and AliBaba, not necessarily Kata Containers.  Those folks are **not** doing a bad job, trust me, but it'd be good to at least have a process defined on whether we want to have a formal representation from Kata Containers here or not.  Or any other project we end up relying on.

Again, the issue was to open the discussion.


The first part of the issue, however, is about having a formal process to add companies representation here.  We've seen, for instance, Microsoft and NVIDIA collaborating a lot with the project, but there's absolutely zero process on how to proceed / how to suggest the companies should be part of the TSC.

I'd be happy with the discussion happening.

**Comment by fidencio** [comment]
> I remember you bringing the argument up in the community meeting of August 10th, and there was some discussion about it from two members of the TSC. They presented their view that, while they agree with you on the need for the TSC to set-up a clear mechanism for expansion and re-election/rotation, they don't see this urgency at this point, since the community is really focused on the merge to kata main.

And it was mentioned that the discussion would happen in the issue, as there were more important things to be discussed in the call.  That never happened till now.  Anyways, I'm happy it seems to be happening now.

**Comment by fitzthum** [comment]
> The first part of the issue, however, is about having a formal process to add companies representation here. We've seen, for instance, Microsoft and NVIDIA collaborating a lot with the project, but there's absolutely zero process on how to proceed / how to suggest the companies should be part of the TSC.

Yeah, we need to amend the charter to be able to add new companies. I am working on that right now.

**Comment by fidencio** [comment]
> Yeah, we need to amend the charter to be able to add new companies. I am working on that right now.

Thanks, that's very much appreciated.

**Comment by dbuono** [comment]
> The first part of the issue, however, is about having a formal process to add companies representation here. We've seen, for instance, Microsoft and NVIDIA collaborating a lot with the project, but there's absolutely zero process on how to proceed / how to suggest the companies should be part of the TSC.

I would have expected Microsoft and NVIDIA's collaborators to come here and show support for this change, then. Maybe you should ask them (and any other company you know is working on the project and would like to have representation) to come here and give their opinion, so the TSC knows this is important to them.

**Comment by fidencio** [comment]
> I would have expected Microsoft and NVIDIA's collaborators to come here and show support for this change, then.

It's hard to anyone to suggest a change on something when there's **zero** process around that.  That's what this issue is about, having a process so companies / projects have a path to do that.  Things get way more inclusive when there's a defined path to take, sincerely.

But I also see your point, thanks for sharing it.

**Comment by dbuono** [comment]
> > I remember you bringing the argument up in the community meeting of August 10th, and there was some discussion about it from two members of the TSC. They presented their view that, while they agree with you on the need for the TSC to set-up a clear mechanism for expansion and re-election/rotation, they don't see this urgency at this point, since the community is really focused on the merge to kata main.
> 
> And it was mentioned that the discussion would happen in the issue, as there were more important things to be discussed in the call. That never happened till now. Anyways, I'm happy it seems to be happening now.

What I meant is that your way of writing the sentence made it sound like in the past two weeks, the TSC did not communicate with you or the community in any way about this. Which is not true. It was briefly discussed less than two weeks ago during a community meeting.

**Comment by fitzthum** [comment]
Ok, I have updated https://github.com/confidential-containers/confidential-containers/pull/56 so that we will have a way to add new companies and so that companies can rotate existing members. Hopefully we can get this merged relatively soon.

**Comment by fidencio** [comment]
> Which is not true. It was briefly discussed less than two weeks ago during a community meeting.

My bad. 11 days, not 14 days.

**Comment by katexochen** [comment]
> They presented their view that, while they agree with you on the need for the TSC to set-up a clear mechanism for expansion and re-election/rotation, they don't see this urgency at this point

I think for a community driven project, it is never (and should never be) the wrong time to talk about participation and democratic processes.

> It would probably help convincing the TSC that this is what the community wants and need right now if there were practical examples of which companies and projects are seeing a need for representation.

I also don't think that "practical examples" should be a requirement to talk about such processes. It should be our aim as a community to be inclusive and open, and it should be **our goal** to grow and actively distribute power across the involved parties.

>  I think there is some mismatch between the expectations and reality of the TSC. I have been thinking about how to address this, and I am working on a plan that includes changing the name of the TSC, explicitly enumerating the TSCs roles and responsibilities, etc.

I would really appreciate this.

Also, it might be a good idea to establish a decision making process for things outside of the TSCs responsibilities. IMO issues like https://github.com/confidential-containers/confidential-containers/issues/143 don't require input by TSC but a documented process to make a decision as a community.

**Comment by magowan** [comment]
I agree that we can/should improve documentation/processes relating to the TSC.
I also agree that a process for rotating hasn't been agreed though I would suggest that there has been a PR open #56 for a long time which hasn't attracted comment from outside those on TSC.
And on the previous couple of occasions over the last year this PR has been highlighted as something for input from community.
On plus side this Issue has been successful in getting some more comment on that open PR so brilliant impact from this issue already.

I have been on holiday for a few weeks so I wasn't here for the last community call on which rotation etc was mentioned. I am certainly on board with focusing on those things the community feel important and I believe the role of the TSC should be to find ways to support the ongoing community work and actions/focus agreed within our community meetings.
I think as our community and projects evolves , so too the TSC needs to evolve in how it supports the goals of the community, It isn't just about code, but also about adoption, relationships with other projects and attracting new topics for discussion in our meetings and new people to the community etc...

For me lets keep making the incremental progress starting with  #56 .
And we then move further to as @fitzthum mentioned "explicitly enumerating the TSCs roles and responsibilities"

**Comment by dbuono** [comment]
> > They presented their view that, while they agree with you on the need for the TSC to set-up a clear mechanism for expansion and re-election/rotation, they don't see this urgency at this point
> 
> I think for a community driven project, it is never (and should never be) the wrong time to talk about participation and democratic processes.
> 
> > It would probably help convincing the TSC that this is what the community wants and need right now if there were practical examples of which companies and projects are seeing a need for representation.
> 
> I also don't think that "practical examples" should be a requirement to talk about such processes. It should be our aim as a community to be inclusive and open, and it should be **our goal** to grow and actively distribute power across the involved parties.

I don't pretend to know what the members of the TSC are thinking but I believe their point was that it didn't seem a top priority for the community. There was a PR open for 6 months with no comments from any member of the community other than the TSC. This PR had also seen virtually no comments. Nobody other than Fabiano spoke in the community meeting.

Since there are other pressing matters (a new release that has already been delayed, a merge to main that ideally should be completed as soon as possible), and the TSC members are also active developers and reviewers, spending time now on this topic didn't seem the main priority to them.

And I was saying that it would help the TSC understanding how important this is if other members of the community (like you are doing now) came to show their support for this PR and #56, and even say "We are company xyz, we would like to be part of the TSC now or in the future, so we welcome a change to the rules so the process is open and well-defined".

**Comment by fidencio** [comment]
To be totally fair, a lot of discssions happened on this topic in private conversations, which seems to be a common standard within the community.  Not saying this is a bad or a good standard, just saying it's common.

Before Tobin's PR was put out, a lot went through deciding the first SC, and we also discussed there what would be the ways to improve it, and ways to keep it open and welcome, but those are lost in google documents I'm afraid.

It seems one of the benifts we'll get on having more public conversations will be, actually, having those discussions being visible.

**Comment by fitzthum** [comment]
> Before Tobin's PR was put out, a lot went through deciding the first SC, and we also discussed there what would be the ways to improve it, and ways to keep it open and welcome, but those are lost in google documents I'm afraid.

The document for the Thursday call has the complete agenda for every community meeting we've had since the project started (including before we had officially adopted any form of open governance). Those meetings are all recorded (save for one or two technical glitches here and there). Sometimes the link to the recording doesn't get added, but we've been pretty good about that. If there are any that are still missing lmk and I will dig them up in Zoom.

The TSC meeting document has the agenda for every TSC meeting. Those are also recorded. For context, we have only had 7.5 TSC meetings in 2023. To be fair these documents contain the agendas for the meetings rather than the minutes, so it might not reflect exactly what happened, but that's where the recordings can help. Of course there are some gaps here and there but these are technical or clerical issues rather than anything sinister.

Occasionally we have spawned extra documents to discuss particular topics. This isn't really an official procedure, but it seems like a reasonable thing to do. Those documents should be linked to the main meeting agenda. I don't recall having a document for discussing the initial formation of governance, but my memory of those days is a bit fuzzy. I checked my google drive/docs history and can't find anything that matches that description. I also glanced at one of [the recordings](https://zoom.us/rec/play/33IqvONsbggTMg1IQnmqMrcCfzoJkQDXW1LuTFvyEJMex6W-9XLzd50vZ900AUFHsase6HZ8bP49oan1.T02hYn3sIxZ37stT?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fzoom.us%2Frec%2Fshare%2FLVkOm3xyys_uJZOCF1oFJpY_gEUmzctnVwAehNnlpgYynPzHkYm0XVriHwi-OlR8.-OR_IvS2N1IWse7Z) where we first talked about governance and didn't find any reference to a document. We do have [this issue](https://github.com/confidential-containers/confidential-containers/issues/9), however, where we flesh out the TSC structure and membership as part of the onboarding process.

> It seems one of the benifts we'll get on having more public conversations will be, actually, having those discussions being visible.

I'm not sure exactly which discussions are being referred to here. My impression is that almost all significant community discussions (such as this one) take place in the open. Of course there are still some private conversations, but there are reasonable times for this (and we can't really control it anyway). To me open governance does not mean nobody can send any direct messages, but that community discussions and decisions are transparent, which I think has been the case. Looking back at the agendas, recordings, issues, etc this seems to have been the case for the founding of the TSC as well.

**Comment by fidencio** [comment]
> We do have [this issue](https://github.com/confidential-containers/confidential-containers/issues/9), however, where we flesh out the TSC structure and membership as part of the onboarding process.

That's what I was referring to, thanks a lot for finding this!

**Comment by fidencio** [comment]
This is my last post on this issue, but I'd like to make it clear that https://github.com/confidential-containers/confidential-containers/pull/152 shows exactly how important it was to have this discussion happening, and how important it's to have a way for organisations to "joining the (SC) gang".

Thanks everyone who helped on this one, very much appreciated.
